import { pariuri } from "@prisma/client";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import { prisma } from "~/server/db";

export const getServerSideProps: GetServerSideProps<{
  posts: pariuri[];
}> = async () => {
  const posts = await prisma.pariuri.findMany();
  posts.sort((a, b) => {
    if (a.echipa1 == b.echipa1) {
      return a.echipa2 < b.echipa2 ? -1 : 1;
    } else {
      return a.echipa1 < b.echipa1 ? -1 : 1;
    }
  });

  return {
    props: { posts },
  };
};

const Home = (
  props: InferGetServerSidePropsType<typeof getServerSideProps>
) => {
  console.log(props);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]"></main>
    </>
  );
};

export default Home;
